POST http://localhost:3000/register/
Content-Type: application/json

{
   "username":"JoeBiden",
   "password":"biden@123",
   "name":"Biden",
   "gender":"male"
}
###



GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjczMDE5MjgzfQ.3IF7p7bWTy_50TGTUUd4k_X454kmsMtFFBspp2k3fnU